data_path: datasets/full_type_table
debug: false
enable_gui: false
folder_name: full_type_table_1
full_view: false
marginal_bbox_size:
  BeerBottle:
  - 0.0750041242892148
  - 0.07501678063491438
  - 0.17886416966013752
  Bottle:
  - 0.10786987392450054
  - 0.10798813922948015
  - 0.14947072082393575
  Bowl:
  - 0.30270121660072713
  - 0.3018975712398707
  - 0.050263775921883025
  Dish:
  - 0.24551679334188137
  - 0.24799606183407674
  - 0.015546586423984599
  HandlessCup:
  - 0.07532540984373132
  - 0.07548351887268456
  - 0.11005229622850005
  Mug:
  - 0.11456040273799706
  - 0.11133156195208502
  - 0.06027486266068399
  WineGlass:
  - 0.1769255866531259
  - 0.1767557433809686
  - 0.13498394573362976
max_bbox_size:
  BeerBottle:
  - 0.06000329943137184
  - 0.06001342450793149
  - 0.17886416966013752
  Bottle:
  - 0.08629589913960042
  - 0.08639051138358413
  - 0.14947072082393575
  Bowl:
  - 0.2421609732805817
  - 0.24151805699189655
  - 0.050263775921883025
  Dish:
  - 0.19641343467350508
  - 0.1983968494672614
  - 0.015546586423984599
  HandlessCup:
  - 0.06026032787498505
  - 0.06038681509814764
  - 0.11005229622850005
  Mug:
  - 0.09164832219039765
  - 0.08906524956166802
  - 0.06027486266068399
  WineGlass:
  - 0.14154046932250072
  - 0.1414045947047749
  - 0.13498394573362976
num_cameras: 36
num_objects: 1
object_types:
- WineGlass
- Bowl
- Bottle
- BeerBottle
- HandlessCup
- Mug
- Dish
reduce_ratio: 2.0
sim_type: table
test_num: 1000
training_num: 30000
validation_num: 1000
voxel_size:
  BeerBottle: 0.0035772833932027504
  Bottle: 0.002989414416478715
  Bowl: 0.004843219465611634
  Dish: 0.003967936989345228
  HandlessCup: 0.002201045924570001
  Mug: 0.001832966443807953
  WineGlass: 0.0028308093864500145
